### ISSUE TITLE
LICENSE?

### ISSUE THREAD

**Issue by AkihiroSuda** [rd235/vdeplug_slirp#1]
@rd235 

As libslirp is licensed under GPL2, I guess vdeplug_slirp needs to be licensed under GPL as well, rather than LGPL?

**Comment by AkihiroSuda** [comment]
ping @rd235

**Comment by rd235** [comment]
You are right... I have released the code of vdeplug_slirp.c under LGPL but the entire plugin must be restricted to GPLv2 as it links (in a dynamic way) libslirp.so. So I have updated the COPYING file and added a LICENSE file to explain the details.

**Comment by AkihiroSuda** [comment]
thank you
